plugins:
  - jekyll-remote-theme
title: CyCIF
description: A Simple Approach to Highly Multiplexed Cell and Tissue Imaging
sass:
  sass_dir: _scss
plugins:
    - jekyll-redirect-from
exclude: []
include: [".nojekyll"]
github: [metadata]
google_analytics: UA-41775478-2
repository: labsyspharm/cycif.org
speech_bucket: www.cycif.org
